kubectl create secret generic multi-keys-secret --from-file=key1.json=/path/to/first/service_account_file.json --from-file=key2.json=/path/to/second/service_account_file.json

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: us-central1-docker.pkg.dev/$PROJECT_ID/distributed-tracing-docker-repo/http-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS_KEY1
          value: /app/keys/key1.json
        - name: GOOGLE_APPLICATION_CREDENTIALS_KEY2
          value: /app/keys/key2.json
        volumeMounts:
        - name: gcp-credentials-key1
          mountPath: /app/keys/key1.json
          subPath: key1.json
        - name: gcp-credentials-key2
          mountPath: /app/keys/key2.json
          subPath: key2.json
      volumes:
      - name: gcp-credentials-key1
        secret:
          secretName: multi-keys-secret
      - name: gcp-credentials-key2
        secret:
          secretName: multi-keys-secret
