apiVersion: v1
kind: Service
metadata:
  name: frontend-service-beyla
spec:
  type: NodePort
  selector:
    app: frontend-app-beyla
  ports:
  - protocol: TCP
    port: 8081 #The service port, can be any of your choose
    targetPort: 8081 #The Pod's port, should be the same where the container is listening
    nodePort: 30009 # The node's port, can be any of your choose
