

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-beyla-trace
  namespace: beyla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app-beyla
  template:
    metadata:
      labels:
        app: frontend-app-beyla
    spec:
      serviceAccountName: beyla-sa
      shareProcessNamespace: true
      containers:
      - name: frontend-app-beyla-container
        image: http-web:minikube #http-out:2
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: DESTINATION_URL
          value: "http://192.168.105.7:30008/"
        - name: PORT
          value: "8081"
        - name: OTEL_SERVICE_NAME
          value: "frontend-application-beyla"
      - name: beyla
        image: grafana/beyla:latest
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_RESOURCE
              - CAP_DAC_READ_SEARCH
              - CAP_SYS_PTRACE
              - CAP_SYS_RESOURCE
              - CAP_PERFMON
              - CAP_BPF
              - CAP_CHECKPOINT_RESTORE
        env:
        - name: BEYLA_SERVICE_NAME
          value: "frontend-app-beyla-container"
        - name: BEYLA_OPEN_PORT
          value: "8081"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: otlp-endpoint
        - name: BEYLA_KUBE_METADATA_ENABLE
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: "frontendbeyla-cluster" #this is the one appearing in grafana cloud as "service"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: otlp-headers
      nodeSelector:
        kubernetes.io/arch: arm64

      
      
    