apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: monitoring
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
