apiVersion: v1
kind: Secret
metadata:
  namespace: beyla
  name: grafana-credentials
type: Opaque
stringData:
  otlp-endpoint: "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
  otlp-headers: "Authorization=Basic MTA1ODYwMTpnbGNfZXlKdklqb2lNVEkwTVRVNU5pSXNJbTRpT2lKemRHRmpheTB4TURVNE5qQXhMVzkwYkhBdGQzSnBkR1V0ZEdWemRDMWlaWGxzWVNJc0ltc2lPaUl4UkRaS1ltc3hiR2RuZG1SMk16UTNOalpyU2paWVlUWWlMQ0p0SWpwN0luSWlPaUp3Y205a0xXVjFMWGRsYzNRdE1pSjlmUT09"