apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemon-test
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      googlecloud:
        project: afb-aws-integration-test
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20
      batch: {}
      resourcedetection:
        detectors: [gcp]
        timeout: 10s
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resourcedetection]
          exporters: [googlecloud]
  volumeMounts:
  - name: gcp-cred
    mountPath: /etc/otelcol/google
  volumes:
  - name: gcp-cred
    secret:
      secretName: secret-name
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/otelcol/google/key1.json
