apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: europe-southwest1-docker.pkg.dev/afb-monitoring-test/distributed-tracing-docker-repo/goapp:general
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.type=backend" #this attribute is displayed in cloud trace and can be filtered
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://collector-service.monitoring.svc.cluster.local:4318/v1/traces" # is using http protocol at port 4318
        # - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        #   value: "collector-service.monitoring.svc.cluster.local:4317" # is using grpc protocol at port 4317
        # - name: OTEL_EXPORTER_OTLP_ENDPOINT
        #   value: "http://collector-service:4317"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: DESTINATION_URL
          value: "https://www.google.com"
        - name: PORT
          value: "8080"
      

      
      
    