apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-sa  # Use the service account for permissions
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.106.0  # Image for the OpenTelemetry Collector
        args: ["--config=/etc/otelcol/otel-config.yaml"]  # Configuration file for the collector (--config command specific to this image), referencing the configuration.yaml (data section) in configmap <mountPath>/<configMapFile>

        ports:
         - name: otlp-grpc
           containerPort: 4317
           protocol: TCP
         - name: otlp-http
           containerPort: 4318
           protocol: TCP
          
        env:
        # - name: GOOGLE_APPLICATION_CREDENTIALS
        #   valueFrom:
        #     secretKeyRef:
        #       name: gcp-sa  # Secret containing Google service account key
        #       key: trace-sa.json  # Key in the secret
          - name: GOOGLE_APPLICATION_CREDENTIALS 
            value: "/etc/otelcol/google/trace-sa.json"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otelcol  # Mount the ConfigMap to this path
        - name: gcp-creds
          mountPath: /etc/otelcol/google          
      volumes: #Here we are defining the volumes and its content
      - name: config-volume #volume-name
        configMap:
          name: otel-collector-config  # ConfigMap name for the collector configuration
      - name: gcp-creds #volume name
        secret:
          secretName: gcp-sa # Secret name for the GCP service account credentials
