apiVersion: v1
kind: Service
metadata:
  name: collector-logs-service #updated for the new otel-logs deployment
  namespace: monitoring
spec:
  selector:
    app: otel-collector-logs #updated for the new otel-logs deployment 
  ports:
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

