
apiVersion: v1
kind: Service
metadata:
  name: expose-app
  namespace: demo-app
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
