apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: monitoring
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
