apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: monitoring
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["sleep"]
    args: ["3600"]
  restartPolicy: Never
