apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetrygen-logs
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetrygen-logs
  template:
    metadata:
      labels:
        app: telemetrygen-logs
    spec:
      containers:
      - name: logs
        image: "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0"
        args: ["logs", "--otlp-insecure", "--rate=3", "--duration=5m", "--otlp-endpoint=$(OTEL_EXPORTER_OTLP_LOGS_ENDPOINT)"]
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "collector-logs-service.monitoring.svc.cluster.local:4317"
        - name: OTEL_RESOURCE_ATTRIBUTES  # Optional resource attributes
          value: "service.name=telemetrygen-logs,service.namespace=monitoring"
